apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exam-api.fullname" . }}
  labels:
    {{- include "exam-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "exam-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "exam-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts | quote }}
            - name: WRITE_DB_URL
              value: "jdbc:postgresql://{{ .Values.database.write.host }}:{{ .Values.database.write.port }}/{{ .Values.database.write.name }}"
            - name: WRITE_DB_USER
              value: {{ .Values.database.write.user | quote }}
            - name: WRITE_DB_PASS
              value: {{ .Values.database.write.password | quote }}
            - name: READ_DB_URL
              value: "jdbc:postgresql://{{ .Values.database.read.host }}:{{ .Values.database.read.port }}/{{ .Values.database.read.name }}"
            - name: READ_DB_USER
              value: {{ .Values.database.read.user | quote }}
            - name: READ_DB_PASS
              value: {{ .Values.database.read.password | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
