server:
  port: 8080

spring:
  main:
    banner-mode: "off"

write:
  url: jdbc:postgresql://pooler-write.default.svc:6432/examdb
  user: examuser
  pass: exampass

read:
  url: jdbc:postgresql://pooler-read.default.svc:6432/examdb
  user: examuser_ro
  pass: readonly
