# Default values for exam-api
replicaCount: 1

image:
  repository: exam-api
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

database:
  write:
    host: "pooler-write.exam.svc"
    port: 6432
    name: "examdb"
    user: "examuser"
    password: "exampass"
  read:
    host: "pooler-read.exam.svc"
    port: 6432
    name: "examdb"
    user: "examuser_ro"
    password: "readonly"

env:
  javaOpts: "-Xms512m -Xmx1g"
