name: Build and Push to Harbor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${HARBOR_REGISTRY}
          username: ${HARBOR_USERNAME}
          password: ${HARBOR_PASSWORD}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${REPO_NAME}:${GITHUB_SHA::7}
          cache-from: type=gha
          cache-to: type=gha,mode=max

env:
  HARBOR_REGISTRY: https://harbor.synesisit.info
  HARBOR_PROJECT: build
  REPO_NAME: exam-app
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
