name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ env.HARBOR_USERNAME }}
          password: ${{ env.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        if: ${{ github.event_name == 'push' }}
        with:
          version: 'v1.28.15'

      - name: Set up Helm
        uses: azure/setup-helm@v4
        if: ${{ github.event_name == 'push' }}
        with:
          version: 'v3.18.3'

      - name: Configure kubeconfig
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "Kubeconfig content:"
          cat $HOME/.kube/config | grep -E 'server|client-key-data|certificate-authority-data|client-certificate-data'

      - name: Verify cluster access
        if: ${{ github.event_name == 'push' }}
        run: |
          kubectl get nodes || echo "kubectl failed: $?"
          kubectl config view --raw
          curl -k https://172.31.70.28:6443

      - name: Create imagePullSecret for Harbor
        if: ${{ github.event_name == 'push' }}
        run: |
          kubectl create secret docker-registry harbor-secret \
            --namespace default \
            --docker-server=${{ env.HARBOR_REGISTRY }} \
            --docker-username=${{ env.HARBOR_USERNAME }} \
            --docker-password=${{ env.HARBOR_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy exam-app using Helm
        if: ${{ github.event_name == 'push' }}
        run: |
          helm upgrade --install exam-app ./helm/exam-app \
            --namespace default \
            --set image.tag=${{ github.sha }}

      - name: Deploy NGINX using Helm
        if: ${{ github.event_name == 'push' }}
        run: |
          helm upgrade --install nginx ./helm/nginx \
            --namespace default \
            --set image.tag=1.21

env:
  HARBOR_REGISTRY: harbor.synesisit.info
  HARBOR_PROJECT: build
  REPO_NAME: exam-app
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
